"""Initial schema: four commerce tables + four slowquery bookkeeping tables.

Revision ID: 0001
Revises:
Create Date: 2026-04-11

Hand-written (not autogenerated) because the exact set of indexes is
load-bearing for the demo: ``orders.user_id``, ``order_items.order_id``,
and ``order_items.product_id`` are deliberately **not** indexed. Spec 00
test 16 greps this file for any ``create_index`` call on those columns
and fails the build if one appears.
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001"
down_revision: str | None = None
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | None = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # Enum type must be created before any table that uses it.
    order_status = postgresql.ENUM(
        "pending",
        "paid",
        "shipped",
        "cancelled",
        name="order_status",
    )
    order_status.create(op.get_bind(), checkfirst=True)

    # --- commerce tables ---------------------------------------------------

    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "products",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("sku", name="uq_products_sku"),
        sa.CheckConstraint("price_cents > 0", name="ck_products_price_cents_positive"),
    )
    op.create_index("ix_products_sku", "products", ["sku"], unique=True)

    op.create_table(
        "orders",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="order_status", create_type=False),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
            name="fk_orders_user_id",
        ),
        sa.CheckConstraint("total_cents >= 0", name="ck_orders_total_cents_nonneg"),
    )
    # DELIBERATELY NO INDEX on orders.user_id — demo depends on seq scans here.

    op.create_table(
        "order_items",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            ondelete="CASCADE",
            name="fk_order_items_order_id",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            ondelete="CASCADE",
            name="fk_order_items_product_id",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_order_items_quantity_positive"),
        sa.CheckConstraint(
            "unit_price_cents >= 0",
            name="ck_order_items_unit_price_cents_nonneg",
        ),
    )
    # DELIBERATELY NO INDEX on order_items.order_id or order_items.product_id.

    # --- slowquery bookkeeping tables --------------------------------------

    op.create_table(
        "query_fingerprints",
        sa.Column("id", sa.String(length=16), primary_key=True),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("call_count", sa.BigInteger(), nullable=False, server_default="1"),
        sa.Column("total_ms", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("p50_ms", sa.Numeric(), nullable=True),
        sa.Column("p95_ms", sa.Numeric(), nullable=True),
        sa.Column("p99_ms", sa.Numeric(), nullable=True),
        sa.Column("max_ms", sa.Numeric(), nullable=True),
    )

    op.create_table(
        "query_samples",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("fingerprint_id", sa.String(length=16), nullable=False),
        sa.Column("params", postgresql.JSONB(), nullable=True),
        sa.Column("duration_ms", sa.Numeric(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column(
            "sampled_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["fingerprint_id"],
            ["query_fingerprints.id"],
            ondelete="CASCADE",
            name="fk_query_samples_fingerprint_id",
        ),
    )
    op.create_index(
        "ix_query_samples_fingerprint_sampled_at",
        "query_samples",
        ["fingerprint_id", "sampled_at"],
    )

    op.create_table(
        "explain_plans",
        sa.Column("fingerprint_id", sa.String(length=16), primary_key=True),
        sa.Column("plan_json", postgresql.JSONB(), nullable=False),
        sa.Column("plan_text", sa.Text(), nullable=False),
        sa.Column("cost", sa.Numeric(), nullable=True),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["fingerprint_id"],
            ["query_fingerprints.id"],
            ondelete="CASCADE",
            name="fk_explain_plans_fingerprint_id",
        ),
    )

    op.create_table(
        "suggestions",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("fingerprint_id", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("sql", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fingerprint_id"],
            ["query_fingerprints.id"],
            ondelete="CASCADE",
            name="fk_suggestions_fingerprint_id",
        ),
    )
    op.create_index("ix_suggestions_fingerprint_id", "suggestions", ["fingerprint_id"])


def downgrade() -> None:
    # Drop in reverse dependency order so the enum type goes last.
    op.drop_index("ix_suggestions_fingerprint_id", table_name="suggestions")
    op.drop_table("suggestions")

    op.drop_table("explain_plans")

    op.drop_index("ix_query_samples_fingerprint_sampled_at", table_name="query_samples")
    op.drop_table("query_samples")

    op.drop_table("query_fingerprints")

    op.drop_table("order_items")
    op.drop_table("orders")

    op.drop_index("ix_products_sku", table_name="products")
    op.drop_table("products")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")

    order_status = postgresql.ENUM(name="order_status")
    order_status.drop(op.get_bind(), checkfirst=True)
